apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagerservice
spec:
  selector:
    matchLabels:
      app: usermanagerservice
  template:
    metadata:
      labels:
        app: usermanagerservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: changjjjjjjjj/user-manager:v0.0.1-alpha
          imagePullPolicy: Always
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"
            - name: FACEBOOK_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-client-secret
                  key: facebookID
            - name: FACEBOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-client-secret
                  key: facebookSecret
            - name: GOOGLE_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-client-secret
                  key: googleID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-client-secret
                  key: googleSecret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbUser
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbName
          volumeMounts:
            - mountPath: /etc/certs
              name: tls-secret
              readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: tls-secret
          secret:
            defaultMode: 420
            secretName: tls-secret
        - name: oauth-secret
          secret:
            defaultMode: 420
            secretName: oauth-client-secret
        - name: db-secret
          secret:
            defaultMode: 420
            secretName: db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagerservice
spec:
  type: NodePort
  selector:
    app: usermanagerservice
  ports:
    - name: server
      port: 3550
      nodePort: 30250
      targetPort: 3550